[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  [functions."*"]
    included_files = ["lib/**"]
    node_bundler = "esbuild"
    external_node_modules = ["pdf2json"]
    # duration = 60 # Commenting out as free tier is hard-capped at 10s usually, strict config might fail deploy if invalid for plan.
